---
- name: Install kubectl
  hosts: [EC2s]
  become: yes  # Use this if you need root privileges
  tasks:
    - name: Ensure required packages are installed
      package:
        name:
          - curl
          - apt-transport-https
        state: present

    - name: Download kubectl
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/v1.31.0/bin/linux/amd64/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: '0755'

    - name: Verify kubectl installation
      command: "kubectl version --client"
      register: kubectl_version_output

    - debug:
        var: kubectl_version_output.stdout
