apiVersion: v1
kind: Service
metadata:
  name: flask-service  # Unique service for Flask app
spec:
  type: LoadBalancer  # Exposes Flask to the internet
  selector:
    app: flask-app  # Targets only the Flask deployment
  ports:
  - protocol: TCP
    port: 80  # Exposed externally via the LoadBalancer
    targetPort: 5002  # Maps to the Flask container's port (5002)
