version: '3.8'

services:
  web:
    build: ./FlaskApp
    ports:
      - "5002:5002"
      - "5003:5003"
    environment:
      MYSQL_DATABASE_USER: your_user
      MYSQL_DATABASE_PASSWORD: your_password
      MYSQL_DATABASE_DB: BucketList
      MYSQL_DATABASE_HOST: db
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: BucketList
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3307:3306"
