apiVersion: v1
kind: Service
metadata:
  name: mysql-service  # Unique service for MySQL
spec:
  selector:
    app: mysql  # Targets the MySQL pods
  ports:
  - protocol: TCP
    port: 3306  # This is the port for MySQL
  clusterIP: None  # Headless service, used for internal communication only
