apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: default
spec:
  replicas: 1  # Typically just one instance for MySQL
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql  # This is the unique label for MySQL pods
    spec:
      containers:
      - name: mysql
        image: wwmezo/db # MySQL image
        imagePullPolicy: Always
        env:
        - name: MYSQL_DATABASE
          value: "BucketList"
        ports:
        - containerPort: 3306  # MySQL runs on port 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-storage
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc  # Use the existing PVC for MySQL storage
